### ISSUE TITLE
launching VM via horizon:  No Valid host was found.  There are not enough Hosts available 

### ISSUE THREAD

**Issue by rhickstedjr** [Ubuntu-Solutions-Engineering/conjure-up#11]
rhicksted@rhicksted-XPS-15-9550:~$ conjure-up --version
conjure-up 0.1.0
rhicksted@rhicksted-XPS-15-9550:~$ juju version
2.0-beta6-xenial-amd64
rhicksted@rhicksted-XPS-15-9550:~$ 
![screenshot from 2016-05-03 14-54-11](https://cloud.githubusercontent.com/assets/12604519/14999878/e255e58a-1140-11e6-8e52-d8bd0e15cc5c.png)

**Comment by battlemidget** [comment]
I've got an updated openstack package in the queue to be put into xenial, until that gets done you can add our ppa and upgrade to the latest openstack packages which has the latest processing scripts to fix all this.

**Comment by battlemidget** [comment]
@rhickstedjr is this still an issue now with the latest packages?

**Comment by rhickstedjr** [comment]
This is fixed in the latest ppas.


Thanks,

Rick

________________________________
